### ISSUE TITLE
Tiny mistakes in the documentation

### ISSUE THREAD

**Issue by Rami-Sabbagh** [luapower/winapi#34]
I've found a mistake in the documentation https://luapower.com/winapi.object
![image](https://user-images.githubusercontent.com/6272475/43414123-8ade033a-943a-11e8-8b97-ccd63a48acaf.png)
I guess the second line should have different description.

**Comment by Rami-Sabbagh** [comment]
Another typo here (https://luapower.com/winapi.basewindowclass):
![image](https://user-images.githubusercontent.com/6272475/43414348-28b53bb4-943b-11e8-8821-4f850270de39.png)

**Comment by Rami-Sabbagh** [comment]
Typo in (https://luapower.com/winapi.basewindowclass)
![image](https://user-images.githubusercontent.com/6272475/43414502-9b19a172-943b-11e8-9855-8b6bd97098ff.png)

**Comment by capr** [comment]
Fixed. Thanks!
